[project]
name = "doc-parser"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.70.0",
    "pymupdf>=1.25.5",
    "pymupdf4llm>=0.0.20",
    "streamlit>=1.44.1",
]
